language: python
python:
  - '3.7'

cache: pip

addons:
 firefox: latest

before_install:
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver
 - geckodriver --version
 - export MOZ_HEADLESS=1

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - staging

env:
  global:
    - SECRET_KEY='7l*om2l-k#b0ec)e(5_3+z)m4p%9fgh3p*t$(f93hgxjaftr@6'
    - DB_NAME=''
    - DB_USER='postgres'
    - DB_PASSWORD=''
    - DB_HOST=''
    - DB_PORT=''

services:
  - postgresql

script:
  - ./manage.py test
